export const OPEN_TRANSCRIPT = "OPEN_TRANSCRIPT";
export const HIDE_TRANSCRIPT = "HIDE_TRANSCRIPT";

export const OPEN_MENU = "OPEN_MENU";
export const HIDE_MENU = "HIDE_MENU";

export const OPEN_HELP = "OPEN_HELP";
export const HIDE_HELP = "HIDE_HELP";

export const OPEN_EXIT_CONFIRMATION_MODAL = "OPEN_EXIT_CONFIRMATION_MODAL";
export const CLOSE_EXIT_CONFIRMATION_MODAL = "CLOSE_EXIT_CONFIRMATION_MODAL";

export const LOAD_NEXT_SLIDE = "LOAD_NEXT_SLIDE";
export const LOAD_BACK_SLIDE = "LOAD_BACK_SLIDE";

export const DISABLE_NEXT = "DISABLE_NEXT";
export const ENABLE_NEXT = "ENABLE_NEXT";

export const DISABLE_BACK = "DISABLE_BACK";
export const ENABLE_BACK = "ENABLE_BACK";
