export const OPEN_TRANSCRIPT = "OPEN_TRANSCRIPT";
export const HIDE_TRANSCRIPT = "HIDE_TRANSCRIPT";

export const OPEN_MENU = "OPEN_MENU";
export const HIDE_MENU = "HIDE_MENU";

export const OPEN_HELP = "OPEN_HELP";
export const HIDE_HELP = "HIDE_HELP";

export const OPEN_EXIT_CONFIRMATION_MODAL = "OPEN_EXIT_CONFIRMATION_MODAL";
export const CLOSE_EXIT_CONFIRMATION_MODAL = "CLOSE_EXIT_CONFIRMATION_MODAL";
